version: "3"

services:
    app:
        container_name: portfolio_app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./:/app
